services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=partner_insurers_service_db'
      - 'POSTGRES_PASSWORD=postgres-secret'
      - 'POSTGRES_USER=postgres-username'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=rabbitmq-secret'
      - 'RABBITMQ_DEFAULT_USER=rabbitmq-username'
    ports:
      - '5672:5672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  postgres-data:
  rabbitmq-data:

networks:
  default:
    name: partner-insurers-service-network
    driver: bridge