services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=partner-insurers-service-db'
      - 'POSTGRES_PASSWORD=postgres-secret'
      - 'POSTGRES_USER=postgres-username'
    ports:
      - '5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=rabbitmq-secret'
      - 'RABBITMQ_DEFAULT_USER=rabbitmq-username'
    ports:
      - '5672'
